defaults:
  - dataset: apple
  - model: vit_tiny
  - optimizer: adam
  - experiments: base
  - _self_

wandb:
  project: "dtu_mlops_project"
  entity: "mlops-kings"
  run_name: "training-run"
  tags: ["training", "vit"]
  notes: "Baseline training with ViT"
  mode: "online"


seed: 42

hydra:
  run:
    dir: outputs/${dataset.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: false